#!/bin/sh -ex

MYSQL="mysql --user=root --password=${MYSQL_PASS} --batch"


# Prepare MySQL database
/etc/init.d/mysql start

## FIXME: username/password here is hard-coded into overlay/usr/local/owntracks/m2s/settings.py

$MYSQL --execute "CREATE DATABASE owntracks;"
$MYSQL --execute "CREATE USER 'a' IDENTIFIED BY 'a';"
$MYSQL --execute "GRANT ALL on owntracks.* TO 'a';"


/etc/init.d/mysql stop

# JPM
# CA certificate/ server cert/key is created in firstboot inithook upon start

mkdir -p /etc/mosquitto/owntracks



cat > /etc/mosquitto/mosquitto.conf <<!EOFmosquitto
#(@) mosquitto.conf pre-configured for OwnTracks
#
autosave_interval 1800

connection_messages true
log_dest stderr
log_dest topic
log_dest file /var/log/mosquitto/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
log_type all
log_type debug
log_timestamp true

password_file /etc/mosquitto/mosquitto.pw
acl_file /etc/mosquitto/mosquitto.acl

persistence true
persistence_location /var/lib/mosquitto/
persistence_file mosquitto.db
persistent_client_expiration 1m

pid_file /var/run/mosquitto.pid

retained_persistence true

listener 1883 127.0.0.1

listener 8883
tls_version tlsv1
cafile /etc/mosquitto/owntracks/ca.crt
certfile /etc/mosquitto/owntracks/mqttitude.crt
keyfile /etc/mosquitto/owntracks/mqttitude.key
require_certificate false

!EOFmosquitto

cat > /etc/mosquitto/mosquitto.pw <<!EOFmosquittopw
!EOFmosquittopw
chown mosquitto /etc/mosquitto/mosquitto.pw
chmod 600 /etc/mosquitto/mosquitto.pw

cat > /etc/mosquitto/mosquitto.acl <<!EOFmosquittoacl
!EOFmosquittoacl
chown mosquitto /etc/mosquitto/mosquitto.acl
chmod 600 /etc/mosquitto/mosquitto.acl

# Create a default configuration for m2s
mkdir -p /usr/local/owntracks/default
cat > /usr/local/owntracks/default/m2s-settings.py <<!EOFm2ssettings
#(@)settings.py

logfile	= '/var/log/mosquitto/m2s.log'		
mqtt_broker = 'localhost'       # default: 'localhost'
mqtt_port = 1883                # default: 1883
mqtt_clientid = 'm2s-backend'   # MUST be set
# mqtt_username = 'jane'
# mqtt_password = 'secret'

# List of topics we should subscribe to
topics = [
        'owntracks/#',
    ]

# optional: if any words in this list are present in a topic
# name, ignore the message

# blocked_topics = [ 'isim', 'jjolie' ]

# Storage
storage_plugin = 'storage.py'
dbname = 'owntracks'
dbuser = 'a'
dbpasswd = 'a'

# data_plugins = None
data_plugins = [
        # dbcolumn=pluginname       path-to-plugin.py
        dict(column='weather',      filename='pl-weather.py'),
        dict(column='revgeo',       filename='pl-revgeo.py'),
]

# The following configuration is made available to plugins through
# the m2s object. A plugin can access
#
#	m2s.cf.replublish_topic   or
#	m2s.cf.name
#	etc.
#
# See pl-republish.py for an example which uses 'republish_topic',
# 'republish_users', 'republish_devices'

plugin_configs = {
	"republish_topic" : "local/loca",
	"republish_users" : [ 'john', ],
	"republish_devices" : [ 'iphone', 'nexus', ],
	"name" : "JP Mens",
}

!EOFm2ssettings
