#!/bin/bash -e
# Generate SSL certificate for MQTTitude

fatal() {
    echo "fatal: $@" 1>&2
    exit 1
}

# Exit if openssl is not available
which openssl >/dev/null || fatal "openssl is not installed"

# JPM
# generate CA certificate

test -d /etc/mosquitto/mqttitude  || mkdir -p /etc/mosquitto/mqttitude
(
	cd /etc/mosquitto/mqttitude
	/usr/local/mqttitude/repo/tools/TLS/generate-CA.sh
)
