#!/bin/bash -e
# Generate SSL certificate for OwnTracks (formerly MQTTitude)

echo "* Regenerating TLS keys/cert for OwnTracks"

. /etc/default/inithooks

fatal() {
    echo "fatal: $@" 1>&2
    exit 1
}

# Exit if openssl is not available
which openssl >/dev/null || fatal "openssl is not installed"

# generate CA certificate

test -d /etc/mosquitto/owntracks  || mkdir -p /etc/mosquitto/owntracks
TARGET=/etc/mosquitto/owntracks  MOSQUITTOUSER=mosquitto /usr/local/owntracks/tools/TLS/generate-CA.sh mqttitude
# chown mosquitto /etc/mosquitto/owntracks/*

sleep 3

chown -R mosquitto /var/log/mosquitto/

# Copy default settings for m2s

test -f /usr/local/owntracks/m2s/settings.py || cp /usr/local/owntracks/default/m2s-settings.py /usr/local/owntracks/m2s/settings.py
